version: '3.7'

networks:
  core_default:
    external:
      name: core_virtual_network
services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfiles/client.dockerfile
    command: tail -F anything
    container_name: ac_app_client_builder
    volumes:
      - ./client/src:/app/src
  web:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    command:
      - /bin/sh
      - -c
      - |
        uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: ac_app
    volumes:
      - ./webapp:/webapp
      - ../core_repo/async_service/:/core/async_service
      - ../core_repo/database/:/core/database
      - ../core_repo/download_service/:/core/download_service
      - ../core_repo/queue_service/:/core/queue_service
      - ../core_repo/security_service/:/core/security_service
      - ../core_repo/session/:/core/session
      - ../core_repo/store_service/:/core/store_service
      - ./.vscode-server:/root/.vscode-server
      - ../static:/downloaded
      - ./client:/client
    ports:
      - 60890:8000
    networks:
      - core_default
    environment:
      - PYTHONPATH=/core
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
