version: '3.7'

networks:
  core_default:
    external:
      name: core_virtual_network
services:
  web:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: ac_app
    volumes:
      - ./webapp:/webapp
      - ../core_repo/database/:/core/database
      - ../core_repo/session/:/core/session
      - ../core_repo/store_service/:/core/store_service
      - ../core_repo/queue_service/:/core/queue_service
      - ./.vscode-server:/root/.vscode-server
    networks:
      - core_default
    environment:
      - PYTHONPATH=/core
