version: '3.7'

networks:
  core_default:
    external: true
    name: core-vn
services:
  web:
    cap_add:
      - NET_ADMIN
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    image: ph-app:1.0
    command:
      - /bin/sh
      - -c
      - |
        uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: ph-app
    volumes:
      - ./webapp:/webapp
      - ../core-repo/async_service/:/core/async_service
      - ../core-repo/database/:/core/database
      - ../core-repo/download_service/:/core/download_service
      - ../core-repo/queue_service/:/core/queue_service
      - ../core-repo/security_service/:/core/security_service
      - ../core-repo/session/:/core/session
      - ../core-repo/store_service/:/core/store_service
      - ./.vscode-server:/root/.vscode-server
      - ../static:/downloaded    
    networks:
      - core_default
    environment:
      - PYTHONPATH=/core
    devices:
      - /dev/net/tun
