from .scraping_service_factory import ScrapingServiceFactory
from .anime1_scraping_service import Anime1ScrapingService
from .copymanga_scraping_service import CopyMangaScrapingService
from .manhuaren_scraping_service import ManhuarenScrapingService
from .mock_manga_scraping_service import MockMangaScrapingService
