version: '3.7'

networks:
  core_default:
    external: true
    name: core-vn
  bt_default:
    external: true
    name: bt_virtual_network

services:
  dmhy:
    container_name: dmhy-job
    image: dmhy-job:1.0
    build:
      context: ./dmhy
      dockerfile: Dockerfile
    command: tail -F anything
    volumes:
      - ./.vscode-server:/root/.vscode-server
      - ../core-repo/download_service/:/core/download_service
      - ../core-repo/store_service/:/core/store_service
      - ../core-repo/async_service/:/core/async_service
      - ./dmhy/src:/src
    environment:
      - PYTHONPATH=/core
  encryption:
    container_name: encryption_job
    build:
      context: ./encryption
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - ../core_repo/store_service:/core/store_service
      - ../core_repo/queue_service:/core/queue_service
      - ../encryption_project/webapp/core/:/core/encrypt_service/
      - ./encryption/src:/src
      - ../encryption_project/webapp/uploaded/:/uploaded
      - ../encryption_project/webapp/encrypted/:/encrypted
      - ./.vscode-server:/root/.vscode-server
    environment:
      - PYTHONPATH=/core
    networks:
      - core_default
