version: '3.7'

networks:
  core_default:
    external: true
    name: core-vn

services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfiles/client.dockerfile
    image: auth-app-client-builder:1.0
    container_name: auth-app-client-builder
    volumes:
      - ./client/src:/app/src
    deploy:
      replicas: 0
  web:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    image: auth-app:1.0
    container_name: auth-app
    command: uvicorn main:app --reload --workers 1 --host auth-app --port 8000 --forwarded-allow-ips "*"
    volumes:
      - ./webapp:/webapp
      - ../core-repo/database/:/core/database
      - ../core-repo/session/:/core/session
      - ./client:/client
    networks:
      - core_default
    environment:
      - PYTHONPATH=/core
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
  test-db:
    container_name: core-test-db
    image: postgres:alpine
    # restart: always
    ports:
      - 65433:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: mydb
    networks:
      - core_default
    deploy:
      replicas: 0
