version: '3.7'

networks:
  core_default:
    external: true
    name: core-vn

services:
  web:
    image: nginx:alpine
    volumes:
      - ../static:/static:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/data/nginx/cache
    container_name: core-nginx
    ports:
      - 80:80
    networks:
      - core_default
  core:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    image: core-python:1.0
    container_name: core-python
    volumes:
      - ./database:/src/database
      - ./src/alembic:/src/alembic
      - ./queue_service:/src/queue_service
      - ./store_service:/src/store_service
      - ./download_service:/src/download_service
      - ./async_service:/src/async_service
      - ./tests:/src/tests
      - ./.vscode-server:/root/.vscode-server
      - ./src/alembic.ini:/src/alembic.ini
      - ./src/Makefile:/src/Makefile
    networks:
      - core_default
    deploy:
      replicas: 0
  db:
    container_name: core-db
    image: postgres:alpine
    # restart: always
    ports:
      - 65432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: mydb
    networks:
      - core_default
  redis:
    container_name: default-redis
    image: redis:alpine
    networks:
      - core_default

